import java.util.*;

//Class in which all the permanent and not changeable data is stored, to ensure the reusability of the code.
 public class Data
{
    private ArrayList<ArrayList<String>> games = new ArrayList<ArrayList<String>>();
        
    private ArrayList<String> titles = new ArrayList<String>();
    private ArrayList<String> sales = new ArrayList<String>();
    private ArrayList<String> platforms1 = new ArrayList<String>();
    private ArrayList<String> platforms2 = new ArrayList<String>();
    private ArrayList<String> releaseDate = new ArrayList<String>();
    private ArrayList<String> developers1 = new ArrayList<String>();
    private ArrayList<String> developers2 = new ArrayList<String>();
    private ArrayList<String> publishers1 = new ArrayList<String>();
    private ArrayList<String> publishers2 = new ArrayList<String>();
    
    //All the data stored and used in this lab.
    public Data()
    {
        titles.add("Minecraft");
        titles.add("Grand Theft Auto V");
        titles.add("Tetris (EA Mobile)");
        titles.add("Wii Sports");
        titles.add("PlayerUnknown's Battlegrounds");
        titles.add("Super Mario Bros.");
        titles.add("Pokémon Red / Green / Blue / Yellow");
        titles.add("Wii Fit and Wii Fit Plus");
        titles.add("Tetris (Nintendo)");
        titles.add("Pac-Man");
        titles.add("Mario Kart Wii");
        titles.add("Mario Kart 8 / Deluxe");
        titles.add("Wii Sports Resort");
        titles.add("Red Dead Redemption 2");
        titles.add("New Super Mario Bros.");
        titles.add("Terraria");
        titles.add("New Super Mario Bros. Wii");
        titles.add("The Elder Scrolls V: Skyrim");
        titles.add("Diablo III");
        titles.add("Pokémon Gold / Silver / Crystal");
        titles.add("Duck Hunt");
        titles.add("Wii Play");
        titles.add("The Witcher 3");
        titles.add("Grand Theft Auto: San Andreas");
        titles.add("Call of Duty: Modern Warfare 3");
        titles.add("Call of Duty: Black Ops");
        titles.add("Grand Theft Auto IV");
        titles.add("Pokémon Sun / Moon / Ultra Sun / Ultra Moon");
        titles.add("Pokémon Diamond / Pearl / Platinum");
        titles.add("Call of Duty: Black Ops II");
        titles.add("Kinect Adventures!");
        titles.add("FIFA 18");
        titles.add("Sonic the Hedgehog");
        titles.add("Nintendogs");
        titles.add("Mario Kart DS");
        titles.add("Call of Duty: Modern Warfare 2");
        titles.add("Pokémon Ruby / Sapphire / Emerald");
        titles.add("Borderlands 2");
        titles.add("Super Mario World");
        titles.add("Frogger");
        titles.add("Lemmings");
        titles.add("Grand Theft Auto: Vice City");
        titles.add("The Last of Us");
        titles.add("The Legend of Zelda: Breath of the Wild");
        titles.add("Brain Age");
        titles.add("Super Mario Bros. 3");
        titles.add("Call of Duty: Ghosts");
        titles.add("Super Smash Bros. Ultimate");
        titles.add("Mario Kart 7");
        titles.add("Super Mario Land");
        titles.add("Gran Turismo 4");
        
        sales.add("200000000");
        sales.add("130000000");
        sales.add("100000000");
        sales.add("82900000");
        sales.add("60000000");
        sales.add("48240000");
        sales.add("47520000");
        sales.add("43800000");
        sales.add("43000000");
        sales.add("39098000");
        sales.add("37320000");
        sales.add("33220000");
        sales.add("33130000");
        sales.add("31000000");
        sales.add("30800000");
        sales.add("30300000");
        sales.add("30300000");
        sales.add("30000000");
        sales.add("30000000");
        sales.add("29490000");
        sales.add("28300000");
        sales.add("28020000");
        sales.add("28000000");
        sales.add("27500000");
        sales.add("26500000");
        sales.add("26200000");
        sales.add("25000000");
        sales.add("24950000");
        sales.add("24730000");
        sales.add("24200000");
        sales.add("24000000");
        sales.add("24000000");
        sales.add("23982960");
        sales.add("23960000");
        sales.add("23600000");
        sales.add("22700000");
        sales.add("22540000");
        sales.add("22000000");
        sales.add("20972500");
        sales.add("20000000");
        sales.add("20000000");
        sales.add("20000000");
        sales.add("20000000");
        sales.add("19080000");
        sales.add("19010000");
        sales.add("19000000");
        sales.add("19000000");
        sales.add("18840000");
        sales.add("18710000");
        sales.add("18370500");
        sales.add("17830000");
        
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Mobile");
        platforms1.add("Wii");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Wii");
        platforms1.add("Game Boy");
        platforms1.add("Multi-platform");
        platforms1.add("Wii");
        platforms1.add("Wii U");
        platforms1.add("Wii");
        platforms1.add("Multi-platform");
        platforms1.add("Nintendo DS");
        platforms1.add("Multi-platform");
        platforms1.add("Wii");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Game Boy Color");
        platforms1.add("NES");
        platforms1.add("Wii");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Nintendo 3DS");
        platforms1.add("Nintendo DS");
        platforms1.add("Multi-platform");
        platforms1.add("Xbox 360");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Nintendo DS");
        platforms1.add("Nintendo DS");
        platforms1.add("Multi-platform");
        platforms1.add("Game Boy Advance");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("PS3");
        platforms1.add("Nintendo Switch");
        platforms1.add("Nintendo DS");
        platforms1.add("Multi-platform");
        platforms1.add("Multi-platform");
        platforms1.add("Nintendo Switch");
        platforms1.add("Nintendo 3DS");
        platforms1.add("Multi-platform");
        platforms1.add("PS2");
        
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("NES");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("Nintendo Switch");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("PS4");
        platforms2.add("Wii U");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("");
        platforms2.add("PSP");
        
        releaseDate.add("18.11.2011");
        releaseDate.add("17.9.2013");
        releaseDate.add("12.9.2006");
        releaseDate.add("19.11.2006");
        releaseDate.add("20.12.2017");
        releaseDate.add("13.9.1985");
        releaseDate.add("27.2.1996");
        releaseDate.add("1.12.2007");
        releaseDate.add("14.6.1989");
        releaseDate.add("1.7.1980");
        releaseDate.add("10.4.2008");
        releaseDate.add("29.5.2014");
        releaseDate.add("25.6.2009");
        releaseDate.add("26.10.2018");
        releaseDate.add("15.5.2006");
        releaseDate.add("16.5.2011");
        releaseDate.add("11.11.2009");
        releaseDate.add("11.11.2011");
        releaseDate.add("16.5.2012");
        releaseDate.add("21.11.1999");
        releaseDate.add("21.4.1984");
        releaseDate.add("2.12.2006");
        releaseDate.add("19.5.2015");
        releaseDate.add("26.10.2004");
        releaseDate.add("8.11.2011");
        releaseDate.add("9.11.2010");
        releaseDate.add("29.4.2008");
        releaseDate.add("18.11.2016");
        releaseDate.add("28.9.2006");
        releaseDate.add("12.11.2012");
        releaseDate.add("4.11.2010");
        releaseDate.add("29.9.2017");
        releaseDate.add("23.6.1991");
        releaseDate.add("21.4.2005");
        releaseDate.add("14.11.2005");
        releaseDate.add("10.11.2009");
        releaseDate.add("21.11.2002");
        releaseDate.add("18.9.2012");
        releaseDate.add("21.11.1990");
        releaseDate.add("5.6.1981");
        releaseDate.add("14.2.1991");
        releaseDate.add("27.10.2002");
        releaseDate.add("14.6.2013");
        releaseDate.add("3.3.2017");
        releaseDate.add("19.5.2005");
        releaseDate.add("23.10.1988");
        releaseDate.add("5.11.2013");
        releaseDate.add("7.12.2018");
        releaseDate.add("1.12.2011");
        releaseDate.add("21.4.1989");
        releaseDate.add("28.12.2004");
        
        developers1.add("Mojang Studios");
        developers1.add("Rockstar North");
        developers1.add("EA Mobile");
        developers1.add("Nintendo EAD");
        developers1.add("PUBG Corporation");
        developers1.add("Nintendo");
        developers1.add("Game Freak");
        developers1.add("Nintendo EAD");
        developers1.add("Nintendo R&D1");
        developers1.add("Namco");
        developers1.add("Nintendo EAD");
        developers1.add("Nintendo EAD");
        developers1.add("Nintendo EAD");
        developers1.add("Rockstar Studios");
        developers1.add("Nintendo EAD");
        developers1.add("Re-Logic");
        developers1.add("Nintendo EAD");
        developers1.add("Bethesda Game Studios");
        developers1.add("Blizzard Entertainment");
        developers1.add("Game Freak");
        developers1.add("Nintendo R&D1");
        developers1.add("Nintendo EAD");
        developers1.add("CD Projekt Red");
        developers1.add("Rockstar North");
        developers1.add("Infinity Ward");
        developers1.add("Treyarch");
        developers1.add("Rockstar North");
        developers1.add("Game Freak");
        developers1.add("Game Freak");
        developers1.add("Treyarch");
        developers1.add("Good Science Studio");
        developers1.add("EA Canada");
        developers1.add("Sonic Team");
        developers1.add("Nintendo EAD");
        developers1.add("Nintendo EAD");
        developers1.add("Infinity Ward");
        developers1.add("Game Freak");
        developers1.add("Gearbox Software");
        developers1.add("Nintendo EAD");
        developers1.add("Konami");
        developers1.add("DMA Design");
        developers1.add("Rockstar North");
        developers1.add("Naughty Dog");
        developers1.add("Nintendo EPD");
        developers1.add("Nintendo SPD");
        developers1.add("Nintendo");
        developers1.add("Infinity Ward");
        developers1.add("Bandai Namco Studios");
        developers1.add("Nintendo EAD");
        developers1.add("Nintendo R&D1");
        developers1.add("Polyphony Digital");
        
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("Sledgehammer");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        developers2.add("Sora Ltd.");
        developers2.add("");
        developers2.add("");
        developers2.add("");
        
        publishers1.add("Mojang Studios");
        publishers1.add("Rockstar Games");
        publishers1.add("Electronic Arts");
        publishers1.add("Nintendo");
        publishers1.add("PUBG Corporation");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Namco");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Rockstar Games");
        publishers1.add("Nintendo");
        publishers1.add("Re-Logic");
        publishers1.add("Nintendo");
        publishers1.add("Bethesda Softworks");
        publishers1.add("Blizzard Entertainment");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("CD Projekt");
        publishers1.add("Rockstar Games");
        publishers1.add("Activision");
        publishers1.add("Activision");
        publishers1.add("Rockstar Games");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Activision");
        publishers1.add("Xbox Game Studios");
        publishers1.add("Electronic Arts");
        publishers1.add("Sega");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Activision");
        publishers1.add("Nintendo");
        publishers1.add("2K Games");
        publishers1.add("Nintendo");
        publishers1.add("Sega");
        publishers1.add("Psygnosis");
        publishers1.add("Rockstar Games");
        publishers1.add("Sony Computer Entertainment");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Activision");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Nintendo");
        publishers1.add("Sony Computer Entertainment");
        
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("505 Games");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("The Pokémon Company");
        publishers2.add("The Pokémon Company");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("The Pokémon Company");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        publishers2.add("");
        
        games.add(titles);
        games.add(sales);
        games.add(platforms1);
        games.add(platforms2);
        games.add(releaseDate);
        games.add(developers1);
        games.add(developers2);
        games.add(publishers1);
        games.add(publishers2);
    }
    
    public ArrayList<ArrayList<String>> getList1()
    {
        return games;
    }
}